################### mysql数据库连接配置 #################
spring:
  thymeleaf:
    cache: false
#    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hos_refactor?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
  security:
    user:
      name: root
      password: root
server:
  port: 9001

mybatis-plus:   #mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml # 1 这两行配置很重要 指定mapperxml位置 和pojo大小写
  type-aliases-package: com.gty.hos.pojo # 2


